# Generated by Django 6.0.7 on 2026-07-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
