# Generated by Django 6.0.7 on 2026-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_contactmessage_status_buynowclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('new', 'New'), ('contacted', 'Contacted')], default='new', max_length=20),
        ),
    ]
