# Generated by Django 6.0.7 on 2026-07-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_contactmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('closed', 'Closed'), ('contacted', 'Contacted')], default='new', max_length=20),
        ),
    ]
