# Generated by Django 6.0.7 on 2026-08-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_productimage_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('new', 'New'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
