# Generated by Django 6.0.7 on 2026-09-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_productcategory_alter_contactmessage_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=100)),
                ('interested_in', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('contacted', 'Contacted'), ('new', 'New')], default='new', max_length=20),
        ),
    ]
