# Generated by Django 6.0.7 on 2026-09-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_popuplead_alter_contactmessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_excel/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('closed', 'Closed'), ('new', 'New')], default='new', max_length=20),
        ),
    ]
