# Generated by Django 6.0.7 on 2026-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_product_sku_productcategory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('new', 'New'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
