# Generated by Django 6.0.7 on 2026-10-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_contactmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
