# Generated by Django 6.0.7 on 2026-10-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('closed', 'Closed'), ('contacted', 'Contacted')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
